version: "3"

networks:
  common:
    driver: bridge

volumes:
  data-volume:

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=astro
      - MONGO_INITDB_ROOT_USERNAME=tvhelp
      - MONGO_INITDB_ROOT_PASSWORD=tvhelp
    volumes:
      - data-volume:/data/db
      - ./mongo_init_script:/docker-entrypoint-initdb.d
    ports:
      - "0.0.0.0:27017-27019:27017-27019"
    networks:
      - common
    restart: always
